"""Token type constants used by AFD acceptors.

These mirror the normalized token types produced by `lexer.py`.
"""
NEWLINE = "NEWLINE"
COMMENT = "COMMENT"
WHITESPACE = "WHITESPACE"

PALAVRA_CHAVE = "PALAVRA_CHAVE"
IDENTIFICADOR = "IDENTIFICADOR"
IDENTIFICADOR_INVALIDO = "IDENTIFICADOR_INVALIDO"
NUMERO_LITERAL = "NUMERO_LITERAL"
STRING_LITERAL = "STRING_LITERAL"
LOGICO_LITERAL = "LOGICO_LITERAL"
OP = "OP"

LPAREN = "LPAREN"
RPAREN = "RPAREN"
LBRACKET = "LBRACKET"
RBRACKET = "RBRACKET"
LBRACE = "LBRACE"
RBRACE = "RBRACE"
COMMA = "COMMA"
SEMICOLON = "SEMICOLON"
COLON = "COLON"
DOT = "DOT"
